### ISSUE TITLE
fail: Microsoft.AspNetCore.SpaServices[0]       'react-scripts' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by eddieaaeon** [Azure-Samples/communication-services-web-calling-hero#1]
When run "dotnet build", it retuned "okay".
However, when run "dotnet run", it returned the following error msg.

fail: Microsoft.AspNetCore.SpaServices[0]
      'react-scripts' is not recognized as an internal or external command,

      operable program or batch file.
      npm ERR! code ELIFECYCLE

npmfail: Microsoft.AspNetCore.SpaServices[0]
      npm ERR! errno 1
npm ERR! acs_calling_sample@0.3.0 start: `rimraf ./build && react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the acs_calling_sample@0.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

fail: Microsoft.AspNetCore.SpaServices[0]
      npm ERR! A complete log of this run can be found in:

Any suggestion would be helpful!!
Thanks!

**Comment by alex-kwan** [comment]
Hi @eddieaaeon I was wondering if you have installed node on your computer? It looks like it can't find react-scripts which is a node dependency for setting up the front end? 

Can you go into your command prompt and run `node -v`

We are looking for something of at least version 12. If you don't have that you can get node here at https://nodejs.org/en/
