### ISSUE TITLE
Non-react version availability

### ISSUE THREAD

**Issue by leijae** [Azure-Samples/communication-services-web-calling-hero#102]
Just wondering if there is a non-react version floating around? I hate to be that guy... but man... that's a whole new can of worms if you're a 1 man band.

**Comment by alkwa-msft** [comment]
At this time we are looking for additional data for customers looking for a non-react sample.

At this time, you can use our Calling SDK's and bind that functionality to HTML elements or any other UI Library/Framework such as VueJS or Angular. 

We also have a calling component that can used as a standalone script tag 
https://github.com/Azure/communication-ui-library/tree/main/samples/StaticHtmlComposites

**Comment by leijae** [comment]
Woo hoo! I knew you were looking out for us little guys!
