### ISSUE TITLE
Q&A: CallingServerClient object

### ISSUE THREAD

**Issue by nhannt97** [Azure-Samples/communication-services-web-calling-hero#119]
For recording call function, I'm having an issue with create a new CallingServerClient object because I'm using nodejs on server side.
Anyone can help me?
https://github.com/Azure-Samples/communication-services-web-calling-hero/blob/public-preview/Calling/Controllers/CallRecordingController.cs#L61

**Comment by alkwa-msft** [comment]
Hello @nhannt97 

Today we only support C# and Java SDKs for Call Recording

Java
https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/call-recording-sample?pivots=programming-language-java

C#
https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/call-recording-sample?pivots=programming-language-csharp

If you look closer at the sample branch with recording you can clearly see it is a typescript/react front-end with a C# backend.

Hopefully this helps and feel free to re-open if you have any further questions.
