### ISSUE TITLE
Microphone selection does not work

### ISSUE THREAD

**Issue by jsandersrocks** [Azure-Samples/communication-services-web-calling-hero#12]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Create sample app and deploy (either local on Azure)
Ensure you computer has more than one possible Microphone
Run app and try to select and use the 2nd, 3rd or 4th mic attached to your system.
Only the first is recognized now matter what you select initially or during the call that first Microphone in the list is used.

### Any log messages given by the failure
>
None

### Expected/desired behavior
>
Should be able to use any of the available microphones

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10, latest corp

### Versions
>

### Mention any other details that might be useful

Zap me on corpnet if you need more!

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ddematheu2** [comment]
Hey Jeff, Thank you for providing information on this issue. The team is looking at this. We will respond with additional details shortly.

**Comment by alex-kwan** [comment]
Thanks for helping us find this issue.

The fix should be in this commit
https://github.com/Azure-Samples/communication-services-web-calling-hero/commit/6c631e9e5a070afb5d938febe8255c0676420bf1
