### ISSUE TITLE
Prevent user from accidentally leaving ACS call

### ISSUE THREAD

**Issue by michal-kluz** [Azure-Samples/communication-services-web-calling-hero#139]
### This issue is for a: (mark with an `x`)
```
- [ x ] bug report
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

I'm trying to find a way to prevent user from accidentally leaving ACS call (using Javascript Call SDK). Right now clicking refresh page will make the user leave the ACS call immediately (with no "Are you sure?" message).

I have tried to prevent default behaviour for onbeforeunload event, for example with the following code in React:
```
  useEffect(() => {
    window.onbeforeunload = (event) => {
      event.preventDefault();
      return "";
    };
    return function allowRefresh() {
      window.onbeforeunload = null;
    };
  }, []);
```
On attempt to leave page, the browser will popup a confirmation window ("Are you sure you want to leave the page?"). But clicking `Cancel` on the popup makes the call disconnect anyway (even though the user chose not to leave page). If this doesn't work, is there any way to prevent user from accidentally leaving ACS call?

### Expected/desired behavior
The ACS call is NOT disconnected when clicking Cancel in Chrome confirmation popup.

### OS and Version?
Windows 10

**Comment by alkwa-msft** [comment]
Hello Michal. Thanks for sharing this issue. We are currently looking into this and will get back to you when we have something to share.

**Comment by prabhjot-msft** [comment]
@michal-kluz This is a known calling SDK issue, we have a feature to address this. Closing this issue, will update once the feature is implemented.
