### ISSUE TITLE
Recording file is empty

### ISSUE THREAD

**Issue by jeyapandian007** [Azure-Samples/communication-services-web-calling-hero#148]
Hi, i am using 

"@azure/communication-calling": "^1.4.4"  followed the VS/ Sample client Solution and created implemented.

All working fine but in BLOB storage the MP4 is empty (black screen), no audio also. how can i troubleshoot this issue ?

Regards.

**Comment by mgamis-msft** [comment]
Hi @jeyapandian007, thanks for filing this issue. We are looking into it now.

**Comment by prprabhu-ms** [comment]
This project does not have a sample that showcases the Azure Communication Services call recording feature.

That [feature is still in public preview](https://docs.microsoft.com/en-us/azure/communication-services/concepts/voice-video-calling/call-recording).

Thanks for giving it a go! I'd recommend asking any related questions with [Azure Communication Services tag Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/azure-communication-services.html) as there are folks with relevant experience in that community.

**Comment by apvarana** [comment]
> Hi, i am using
> 
> "@azure/communication-calling": "^1.4.4" followed the VS/ Sample client Solution and created implemented.
> 
> All working fine but in BLOB storage the MP4 is empty (black screen), no audio also. how can i troubleshoot this issue ?
> 
> Regards.

Hi
Did it finally work, we are not able to retrieve the recording. What are the exact steps to be followed for recording, what configurations are required for event grids
