### ISSUE TITLE
Unable to publish azure application

### ISSUE THREAD

**Issue by Rutul7** [Azure-Samples/communication-services-web-calling-hero#158]
We are not able to publish this application on our production server.
We are getting following error continuously.

The command "npm run build" exited with code 1.	Calling
Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory	Calling	EXEC	0
1: 00007FF6406B481F napi_wrap+110783
 2: 00007FF640657F26 v8::base::CPU::has_sse+61862
 3: 00007FF640658E26 node::OnFatalError+294
 4: 00007FF640F323BE v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF640F1718D v8::SharedArrayBuffer::Externalize+781
 6: 00007FF640DC02CC v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1516
 7: 00007FF640DCB6EA v8::internal::Heap::ProtectUnprotectedMemoryChunks+1258
 8: 00007FF640DC8829 v8::internal::Heap::PageFlagsAreConsistent+2457
 9: 00007FF640DBD3D1 v8::internal::Heap::CollectGarbage+2049
10: 00007FF640DBB5D5 v8::internal::Heap::AllocateExternalBackingStore+1349
11: 00007FF640DDBA3B v8::internal::Factory::NewFillerObject+203
12: 00007FF640B0A0B1 v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+1409
13: 00007FF640FBB27D v8::internal::SetupIsolateDelegate::SetupHeap+465325
14: 0000010F5A3E3FD8 
RpcIpcMessagePortClosedError: Process 26036 exited with code "134" [null]
Issues checking service aborted - probably out of memory. Check the `memoryLimit` option in the ForkTsCheckerWebpackPlugin configuration.
If increasing the memory doesn't solve the issue, it's most probably a bug in the TypeScript or EsLint.
Failed to compile.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! errno 1
2>Build failed. Check the Output window for more details.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========
npm ERR! azure_communication_services_calling_sample@1.0.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the azure_communication_services_calling_sample@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by edwardlee-msft** [comment]
Closing out on this issue as there has been no update for the past 2 weeks.
Please submit a new issue if you require further assistance.
