### ISSUE TITLE
Giving Screen control  while screen share

### ISSUE THREAD

**Issue by TapanKumarBarik** [Azure-Samples/communication-services-web-calling-hero#20]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by JamesBurnside** [comment]
Hi @TapanKumarBarik thanks for the feature request! Unfortunately the ACS SDK does not support this feature today so we cannot bring it to the sample apps. I do encourage you however to file the feature request under Azure/Communication for best visibility and traction: https://github.com/Azure/Communication/issues/new/choose
