### ISSUE TITLE
Deploy to Azure not working

### ISSUE THREAD

**Issue by bushra-aekay** [Azure-Samples/communication-services-web-calling-hero#212]
Although there is a button called 'deploy to azure' in README.md, the following error is received once redirected to azure: 

There was an error downloading the template from URI 'https://raw.githubusercontent.com/Azure-Samples/communication-services-web-calling-hero/main/deploy/azuredeploy.json'. Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint. To deploy this template, download the template manually and paste the contents in the 'Build your own template in the editor' option below.

**Comment by dmceachernmsft** [comment]
Hi @bushra-aekay! Thanks for filing the issue! I apologize for the late response. are you still encountering the issue that you are running into here? We are taking a look into it now as well!

**Comment by dmceachernmsft** [comment]
Closing issue as new release cut and last customer interaction is old. Please re open the issue if the problem persists
