### ISSUE TITLE
Blazor Sample

### ISSUE THREAD

**Issue by sowsan** [Azure-Samples/communication-services-web-calling-hero#23]
Can we also get a Blazor based sample ? https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor

**Comment by JamesBurnside** [comment]
Hi @sowsan, thanks for reaching out! Unfortunately we don't have the time currently to port the samples to Blazor 😢 One of our engineers (@svanvliet) did hack around with ACS and Blazor so I encourage you to check out their sample: https://github.com/svanvliet/acs-messaging-app
As we evolve our samples and GitHub page we are looking to add a section highlighting awesome community projects using ACS. If you do end up writing an open source project with ACS and Blazor we'd love to reference it on our GitHub page for other engineers to make use of and empower their work!

**Comment by sowsan** [comment]
Thanks for your quick response @JamesBurnside. Since there is a lot of work going on MAUI and Blazor using C# as first party language for the development for both client and server side, it would be great to have a Microsoft SDK for azure communication service using.NET core. Today to make it work we have to create a wrapper for the JS SDK.e.g, https://www.twilio.com/blog/build-video-chat-app-asp-net-core-blazor-webassembly-twilio-video

**Comment by alex-kwan** [comment]
@sowsan  If you have additional requests for other samples. We suggest that you re-post this issue in the azure/communications repo. 

https://github.com/Azure/Communication

From there it can be properly triaged and backlogged. This repository is specifically for this sample. We might be able to better serve you if you can post your issue at azure/communication. Thanks!
