### ISSUE TITLE
Video is not relayed from Android to desktop client 

### ISSUE THREAD

**Issue by oteinone** [Azure-Samples/communication-services-web-calling-hero#40]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 1. Deploy the solution
> 2. Create a meeting with a desktop client
> 3. Join the room with a mobile client
> 4. Mobile client video is never shown on the desktop client

### Any log messages given by the failure
> log.browser.ts:10 azure:ACS:warning 06/04/2021, 17:30:49:456 CallClient3:CallStack:MA:webrtc2-1:SSM Sender with media type Video does not exist, do not update media stream

### Expected/desired behavior
> Mobile video is shown on desktop client when video is turned on

### OS and Version?
> Windows 10 (Chrome 89.0.4389.114, 32 bit)
> Android 10 (Chrome 87.0.4280.141)

### Versions
> Latest version cloned from github

### Mention any other details that might be useful

I tried both WLAN and mobile networks. From desktop client to desktop client everything seems to work.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by alkwa-msft** [comment]
I was able to have it working on my pixel 4

I chatted with another dev that works on the calling SDK team.
He was suggesting if you can open a ticket at https://github.com/Azure/communication
If you can list your phone model, os , browser version that would help him debug the issue
