### ISSUE TITLE
Got 403 error when join with teams meeting link

### ISSUE THREAD

**Issue by katyaechodxai** [Azure-Samples/communication-services-web-calling-hero#45]
### Error description

Error occurs when trying to join to the meeting with Microsoft Teams meeting link

### Minimal steps to reproduce
>
1. Download communication-service-web-calling-hero
2. Create Azure Communication Service and copy Connection String
3. Configure communication-service-web-calling-hero with Connection String from previous step.
4. Start meeting in Microsoft Teams and copy meeting link.
5. Modify /communication-services-web-calling-hero/blob/main/Calling/ClientApp/src/core/sideEffects.ts file on 333 line to join to meeting with Team Meeting link instead of groupId:

```
 call = await callAgent.join({meetingLink: "TEAM_MEETING_LINK"}, callOptions);
```
6. Run communication-service-web-calling-hero application
7. Click on "Start call" button from screenshot and then error occurs.

### Screenshots
1. 
![image](https://user-images.githubusercontent.com/79269400/114556904-d42eb380-9c71-11eb-8432-2b4cb7781dcf.png)
2. 
![image](https://user-images.githubusercontent.com/79269400/114557381-47382a00-9c72-11eb-8f2f-2d8fa238bccf.png)
3.
![image](https://user-images.githubusercontent.com/79269400/114557660-8f574c80-9c72-11eb-828b-c0d8a553bf20.png)

4. Error Response
![image](https://user-images.githubusercontent.com/79269400/114559229-2d97e200-9c74-11eb-988e-898d471e6216.png)

5. BTW in Microsoft Teams Admin Center Setting for Meeting to allow external users to join a meeting was enabled

![image](https://user-images.githubusercontent.com/79269400/114558299-32a86180-9c73-11eb-9027-550890be7e52.png)

### Expected/desired behavior
Connect to Teams Meeting via Communication Service through communication-service-web-calling-hero app like external user.

### OS and Version
Windows 10
Chrome Version 89.0.4389.114 (Official Build) (64-bit)

### Versions
```
"@azure/communication-calling": "1.0.0",
"@azure/communication-common": "1.0.0",
"@azure/communication-identity": "1.0.0",
```

**Comment by alkwa-msft** [comment]
@PorterNan can you please check out this and see if we can help out @katyaechodxai

**Comment by akania** [comment]
@katyaechodxai thank you for reporting, ACS + Teams meeting interop is currently in preview phase, 403/5222 indicates that your Teams tenant wasn't configured to enable interop with ACS. 
To enable it please fill out and send [this form](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR21ouQM6BHtHiripswZoZsdURDQ5SUNQTElKR0VZU0VUU1hMOTBBMVhESS4u)



More information available in our  [public documentation](https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/get-started-teams-interop?pivots=platform-web)
