### ISSUE TITLE
Missing Group-Calling.zip in latest build fails deployment in Azure

### ISSUE THREAD

**Issue by jcnovoa** [Azure-Samples/communication-services-web-calling-hero#50]
The following link 
http://github.com/azure-samples/communication-services-web-calling-hero/releases/latest/download/group-calling.zip
in the https://github.com/Azure-Samples/communication-services-web-calling-hero/blob/main/deploy/azuredeploy.json
gives a 404 as the latest build only has 2 assets (from 21 hour ago)

**Comment by prprabhu-ms** [comment]
Thanks for reporting that, and sorry about the breakage.

I'll see why the source tarball wasn't uploaded.

**Comment by prprabhu-ms** [comment]
FTR: I created the last release as a draft, and then published it. The Github actions we have setup to create the `group-calling.zip` artifact only triggers when a new release is created, not when a draft is published.

I've created a new release to unbreak the deployment flow.

Will take an AI to fix the actions as well.

**Comment by prprabhu-ms** [comment]
Verified that the `Deploy to Azure` badge now works from github web.

Please reopen if you still see failures.
Thanks again!
