### ISSUE TITLE
Sample not working in mobile web (Chrome and Safari)

### ISSUE THREAD

**Issue by aparnaji** [Azure-Samples/communication-services-web-calling-hero#53]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting

- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Deploy sample on azure web app and open in browser, only first page displays, if you try starting a call it says "Learn more about browsers and platforms supported by the web calling SDK""
### Any log messages given by the failure
>

### Expected/desired behavior
>
It should allow to start and participate in call from mobile
### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
iphone 6S .. chrome browser
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by prprabhu-ms** [comment]
Hi,
Thanks for reporting this issue.

This issue might be specific to the platform you're running on. Could you provide some details on the OS and browser you're using (including major versions)?

**Comment by aparnaji** [comment]
![Uploading DFEA9958-D4AC-4C80-95A1-98442819C856.jpeg…]()

**Comment by aparnaji** [comment]
![Uploading 72EE4549-9503-40D7-96B8-FFEC192AE40A.jpeg…]()

**Comment by aparnaji** [comment]
ios 14.2; Chrome Version 87.0.4280.163

**Comment by allenplusplus** [comment]
Hi @aparnaji , currently we do not support using chrome on iOS for the Calling Sample and do not plan to support it in the future.  You could try to work around this by changing the code in your cloned/forked version of the repo and removing the `isOnIphoneAndNotSafari()` check.

**Comment by alkwa-msft** [comment]
Please refer to this browser support matrix for understanding which platforms/browsers we support at this time.
https://docs.microsoft.com/en-us/azure/communication-services/concepts/voice-video-calling/calling-sdk-features#calling-client-library-browser-support
