### ISSUE TITLE
iOS 14.6 + Safari not loading

### ISSUE THREAD

**Issue by M365-DenzilFernandes** [Azure-Samples/communication-services-web-calling-hero#68]
Learn more about browsers and platforms supported by the web calling sdk

That is the message I'm receiving after I click Start Call. No issues in Chrome on the iOS device.

I am using a straight Azure Deploy (Not forked). Everything works in a browser on the desktop. However some issues on iOS Safari 

Is there something I need to enable for iOS to use this sample? Thanks for your assistance.

**Comment by alkwa-msft** [comment]
There was an issue where two call clients were being used in the code. I am creating a pull request to consolidate on this and we should have something fixed soon.  I can reply on this issue again when it is resolved.

**Comment by alkwa-msft** [comment]
This change 4d32f209ca525a085a7b4ec884c878d1303ff53d helped with some of the rendering issues that folks on ios may run into. 

You mentioned there were "some" iOS safari issues. I was wondering if you might able to elaborate further?
