### ISSUE TITLE
I can't hear sound from android web browser

### ISSUE THREAD

**Issue by 2jisu** [Azure-Samples/communication-services-web-calling-hero#69]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Window web browser can't hear sound from android web browser. 
   But android web browser can hear sound from window web browser.

### Any log messages given by the failure
> None

### Expected/desired behavior
> Window user can hear sound from android web browser.

### OS and Version?
> Windows 10 / Android 10 

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by alkwa-msft** [comment]
Can you share your android device as well?
