### ISSUE TITLE
CallClient is trying to reinitialize whenever I resize the window while the configuration page is loaded

### ISSUE THREAD

**Issue by rdweaver** [Azure-Samples/communication-services-web-calling-hero#8]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

1. Open the sample app as is.
2. Click the button to start a call
3. When the configuration page is loaded, resize the browser window and a new call client will try to be created, when one already exists. This will throw the error in the console.

### Any log messages given by the failure

index.js:1 Error: A Call Agent instance has already been created.Please dispose of it before creating a new Call Client instance
    at f.<anonymous> (sdk.bundle.js:247)
    at Generator.next (<anonymous>)
    at sdk.bundle.js:247
    at new Promise (<anonymous>)
    at o (sdk.bundle.js:247)
    at f.createCallAgent (sdk.bundle.js:247)
    at f.<anonymous> (sdk.bundle.js:4)
    at Generator.next (<anonymous>)
    at sdk.bundle.js:4
    at new Promise (<anonymous>)
    at i (sdk.bundle.js:4)
    at f.o.value (sdk.bundle.js:4)
    at sideEffects.ts:155
console.<computed> @ index.js:1
(anonymous) @ sideEffects.ts:226
async function (async)
(anonymous) @ sideEffects.ts:113
(anonymous) @ index.js:8
initCallClient @ Configuration.ts:33
(anonymous) @ Configuration.tsx:61
commitHookEffectList @ react-dom.development.js:22030
commitPassiveHookEffects @ react-dom.development.js:22064
callCallback @ react-dom.development.js:336
invokeGuardedCallbackDev @ react-dom.development.js:385
invokeGuardedCallback @ react-dom.development.js:440
flushPassiveEffectsImpl @ react-dom.development.js:25392
unstable_runWithPriority @ scheduler.development.js:697
runWithPriority$2 @ react-dom.development.js:12149
flushPassiveEffects @ react-dom.development.js:25361
(anonymous) @ react-dom.development.js:25240
workLoop @ scheduler.development.js:641
flushWork @ scheduler.development.js:596
performWorkUntilDeadline @ scheduler.development.js:203

### Expected/desired behavior
I do NOT expect a new call client to be created ever time the browser window resizes.

### Mention any other details that might be useful
This error causes problems downstream with the acs user showing as not online. See this for an example of a downstream problem. https://github.com/Azure/Communication/issues/114

**Comment by alex-kwan** [comment]
This is most likely a bug that tries to initialize the call client when that React components starts to re-render. Will check it out next week.

**Comment by alex-kwan** [comment]
I think we have solved this issue with this commit.
https://github.com/Azure-Samples/communication-services-web-calling-hero/commit/a024279d5849f8b462e73268aeeaa31f78dc7bc9

I was wondering if you might be able to verify and get back to us? I will assume if theres no answer in a few weeks I will just close this as well :)

**Comment by rdweaver** [comment]
Looks good
